name: 'CI'

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
  # This workflow is callable by other workflows
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-lint-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-lint-${{ env.cache-name }}-
      - run: npm ci
      - run: npm install -g solhint
      - run: solhint contracts/**/*.sol

  tests_full:
    runs-on: ubuntu-latest
    steps:
      - name: "step-log-ref"
        run: |
          echo "[C] github.ref: ${{github.ref}}"
      - name: "step-log-event_name "
        run: |
          echo "[C] github.event_name : ${{github.event_name }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-test-unit-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-test-unit-${{ env.cache-name }}-
      - run: npm ci
      - name: Run Hardhat
        run: |
          npx hardhat node &
        env:
          ALCHEMY_URL: ${{secrets.ALCHEMY_URL}}
      - name: Compile contracts
        run: |
          npx hardhat compile --force
        env:
          ALCHEMY_URL: ${{secrets.ALCHEMY_URL}}
      - name: Run tests
        run: npm run test:full:cover
        env:
          ALCHEMY_URL: ${{secrets.ALCHEMY_URL}}
      - name: Delete dbg files
        run: find ./artifacts/* -name "*.dbg.json" -type f -delete
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/

  coverage:
    runs-on: ubuntu-latest
    needs: [tests_full]
    if: ${{ success() && github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage/
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        if: "${{ env.CC_TEST_REPORTER_ID != '' }}"
        with:
          coverageLocations: |
            ${{ github.workspace }}/coverage/lcov.info:lcov

  dockerbuild:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t "testimage:latest" .


