name: 'Publish'

on:
  push:
    tags:
      - '**'

jobs:
   publish-npm:
    needs: [lint, tests_full]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Compile contracts
        run: |
          npx hardhat compile --force
        env:
          ALCHEMY_URL: ${{secrets.ALCHEMY_URL}}
      - name: Delete dbg files
        run: find ./artifacts/* -name "*.dbg.json" -type f -delete
      - name: Delete useless files
        run: rm -rf ./artifacts/build-info/*
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
